In [2]:
# 7.3
from mtm026 import *

# För att kunna lösa allt numeriskt inför vi enhetsvärden på alla variabler
P0 = EI = L = H = 1

# Definiera styvheterna
K = np.zeros((9, 9))
K_sig = np.zeros((9, 9))

# Skapa elementstyvheter
Ke1 = Ke_balk(EI=EI, L=L)
Ke2 = Ke_balk(EI=EI, L=L)
assem(K, Ke1, dofs=[1, 2, 3, 4])
assem(K, Ke2, dofs=[3, 4, 5, 6])

# För den stela balken kan vi ge den ett jättehögt värde, alltifrån 1e6 - 1e12 gånger större
Ke3 = Ke_balk(EI=EI*10**12, L=H)
assem(K, Ke3, dofs=[7, 4, 8, 9])


# Skapa spänningsstyvhetsmatriser, men bara den stela balken har en kraft som inte är noll
Ke3_sig = Ke_sigma_balk(P=P0, L=H)
assem(K_sig, Ke3_sig, dofs=[7, 4, 8, 9])

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.13333333,  0.        ,
         0.        ,  0.1       , -0.1       , -0.03333333],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.1       ,  0.        ,
         0.        ,  1.2       , -1.2       ,  0.1       ],
       [ 0.        ,  0.        ,  0.        , -0.1       ,  0

In [3]:
# Definiera våra fria frihetsgrader
free_dofs = [2,4,6,8,9]

# Reducera till enbart fria frihetsgrader
K_red = extract_block(K, free_dofs, free_dofs)
K_sigma_red = extract_block(K_sig, free_dofs, free_dofs)

In [26]:
# Lös det generaliserade egenvärdesproblemet och få ut hur många gånger
# större krafter måste vara (varje λ) samt hur den knäckformen ser ut (varje kolonn i a ger en ny form)
λ, a = eig(K_red, K_sigma_red)

# Sortera för att få den lägsta knäckkraften först
sortingOrder = np.argsort(λ)
λ = λ[sortingOrder]

# Sortera formerna på samma sätt
a = a[:, sortingOrder]


displayvar("λ_1",np.real(λ[0]))
displayvar("a_1",a[:,0])

# facit P = 6EI/LH = 6 i vårt fall.


<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [5]:
# 7.12

# Enhetsvärden på allting igen
P0 = EI = L = H = 1

K = np.zeros((9, 9))
K_sig = np.zeros((9, 9))

# ALla tre är lika styva, behöver bara en Ke
Ke = Ke_balk(EI=EI, L=L)


assem(K, Ke, dofs=[1, 2, 3, 4])
assem(K, Ke, dofs=[3, 4, 5, 6])
assem(K, Ke, dofs=[7, 4, 8, 9])

# Som i 7.3, bara en balk har en normalkraft
Ke3_sig = Ke_sigma_balk(P=P0, L=L)

assem(K_sig, Ke3_sig, dofs=[7, 4, 8, 9])

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.13333333,  0.        ,
         0.        ,  0.1       , -0.1       , -0.03333333],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.1       ,  0.        ,
         0.        ,  1.2       , -1.2       ,  0.1       ],
       [ 0.        ,  0.        ,  0.        , -0.1       ,  0

In [6]:
# Reducera till enbart fria frihetsgrader
free_dofs = [2,3,4,6, 8, 9]

K_red = extract_block(K, free_dofs, free_dofs)
K_sigma_red = extract_block(K_sig, free_dofs, free_dofs)


In [7]:
# Lös egenvärdesproblemet 
λ, a = eig(K_red, K_sigma_red)

# Sortera allt
sortingOrder = np.argsort(λ)
λ = λ[sortingOrder]
a = a[:, sortingOrder]
displayvar("λ_1",np.real(λ[0]))
displayvar("a_1",a[:,0])
# facit P = 1.8225


 λ = [  1.82648482+0.j  23.49185496+0.j 100.68166021+0.j          inf+0.j
          inf+0.j          inf+0.j]
[ 8.71841175e-02  7.91148005e-19 -1.74368235e-01  8.71841175e-02
 -5.72799400e-01 -7.91387658e-01]


In [8]:
# 7.17

# Definiera enhetsstorheter
P0 = L = EI = 1 # Enhetsvärden

K = np.zeros((6, 6))
K_sig = np.zeros((6, 6))

Ke1 = Ke_balk(EI=EI, L=L)
# Andra balken är jättestyv
Ke2 = Ke_balk(EI=EI*1e12, L=L) 

assem(K, Ke1, dofs=[1, 2, 3, 4])
assem(K, Ke2, dofs=[3, 4, 5, 6])

# Kraften går genom båda balkarna, frilägg och se hur det stämmer
Ke1_sig = Ke_sigma_balk(P=P0, L=L)
Ke2_sig = Ke_sigma_balk(P=P0, L=L)
assem(K_sig, Ke1_sig, dofs=[1, 2, 3, 4])
assem(K_sig, Ke2_sig, dofs=[3, 4, 5, 6])


array([[ 1.2       ,  0.1       , -1.2       ,  0.1       ,  0.        ,
         0.        ],
       [ 0.1       ,  0.13333333, -0.1       , -0.03333333,  0.        ,
         0.        ],
       [-1.2       , -0.1       ,  2.4       ,  0.        , -1.2       ,
         0.1       ],
       [ 0.1       , -0.03333333,  0.        ,  0.26666667, -0.1       ,
        -0.03333333],
       [ 0.        ,  0.        , -1.2       , -0.1       ,  1.2       ,
        -0.1       ],
       [ 0.        ,  0.        ,  0.1       , -0.03333333, -0.1       ,
         0.13333333]])

In [9]:
# Ställ upp fria dofs och reducera
free_dofs = [3,4, 5, 6] 
K_red = extract_block(K, free_dofs, free_dofs)
K_sigma_red = extract_block(K_sig, free_dofs, free_dofs)

In [10]:
# Lös egenvärdesproblemet
λ, a = eig(K_red, K_sigma_red)
sortingOrder = np.argsort(λ)
# Sort alpha
λ = λ[sortingOrder]
# Use the same indices to sort a
a = a[:, sortingOrder]
print(f"lastmultiplikatorer α = {λ}")
displayvar("λ_1",np.real(λ[0]))
displayvar("λ_2",np.real(λ[1]))
# facit P = 0.860334^2 EI/L**2 = 0.7402 EI/L**2
displayvar("a_1",a[:,0])
displayvar("a_2",a[:,1])


lastmultiplikatorer α = [7.39913311e-01+0.j 1.20022162e+01+0.j 8.76959191e+12+0.j
 4.34657022e+13+0.j]
Kritisk last P_kr = (0.739913311494905+0j) N
Kritisk last P_kr2 = (12.002216201690747+0j) N
[0.24758296 0.46453657 0.71211953 0.46453657]
[-0.75592944  0.37796298 -0.37796647  0.37796298]


In [11]:

# Den här går igenom hur man kan lösa allt symboliska, men det fungerar bara i vissa specialfall.

from mtm026 import *

# Ställ upp symboliska variabler
EI, L, P = sp.symbols("EI L P")
Ke = Ke_balk(EI,L)
Ksig = Ke_sigma_balk(P, L)

# Illustrera systemet
display(Ke)
display(Ksig)



Matrix([
[ 12*EI/L**3,  6*EI/L**2, -12*EI/L**3,  6*EI/L**2],
[  6*EI/L**2,     4*EI/L,  -6*EI/L**2,     2*EI/L],
[-12*EI/L**3, -6*EI/L**2,  12*EI/L**3, -6*EI/L**2],
[  6*EI/L**2,     2*EI/L,  -6*EI/L**2,     4*EI/L]])

Matrix([
[ 6*P/(5*L),     P/10, -6*P/(5*L),     P/10],
[      P/10, 2*L*P/15,      -P/10,  -L*P/30],
[-6*P/(5*L),    -P/10,  6*P/(5*L),    -P/10],
[      P/10,  -L*P/30,      -P/10, 2*L*P/15]])

In [12]:
# Reducera för att illustrera
Ke_red = extract_block(Ke,[3,4],[3,4])
Ksig_red = extract_block(Ksig,[3,4],[3,4])

display(Ke_red)
display(Ksig_red)

Matrix([
[12*EI/L**3, -6*EI/L**2],
[-6*EI/L**2,     4*EI/L]])

Matrix([
[6*P/(5*L),    -P/10],
[    -P/10, 2*L*P/15]])

In [13]:
# Lös egenvärdesproblemet (A-λB)x = 0 => inv(B)*A*x = λx vilket blir ett vanligt egenvärdesproblem
# som kan lösas med .eigenvals() från sympy

A = Ksig_red.inv()*Ke_red

displayvar("eigvals",A.eigenvals())
displayvar("eigvecs",A.eigenvects())


<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [14]:
# Substituera in värden för att beräkna kritisk last

B = A.subs({EI:1,L:1,P:1})
Beigs = list(B.eigenvals().keys())

displayvar("eigs",Beigs)
display(Beigs[0].round(3),Beigs[1].round(3))


<IPython.core.display.Math object>

2.486

32.181

In [15]:
# Ställ upp problemet numeriskt med antagna värden EI = 1, L = 1, P = 1
Ke_num = Ke_balk(1,1)
Ksig_num = Ke_sigma_balk(1,1)

# Vi har bara ett element, så reducera till frihetsgrad 3, 4
Ke_red_num = extract_block(Ke_num,[3,4],[3,4])
Ksig_red_num = extract_block(Ksig_num,[3,4],[3,4])

# Specifikt för den här implementationen, byt variabeltyp för att inte krascha
Ke_red_num = np.array(Ke_red_num).astype(np.float64)
Ksig_red_num = np.array(Ksig_red_num).astype(np.float64)

# Lös egenvärdesproblemet och sortera alla egenvärden
alpha,a = eig(Ke_red_num,Ksig_red_num)
alpha = np.real(alpha[np.argsort(alpha)])

# Jämföra detta med ovan värde!
displayvar("α_1",alpha[0])



<IPython.core.display.Math object>

In [19]:
# Exempel på att ta fram kritisk last för godtyckligt antal balkelement.
# Standardvärdena är för Euler 2, men de fria frihetsgraderna kan ändras för att ge olika
# Begränsa er till ca 100 element eftersom lösningen blir väldigt långsam för stora matriser.

from mtm026 import *
import matplotlib.pyplot as plt

# Antal balkelement
nr_balk = 10

# Definiera alla värden
L = 1/nr_balk
EI = P = 1
k = 1

# Skapa globala matriser
K = np.zeros((2*nr_balk+2,2*nr_balk+2))
Ksig = np.zeros((2*nr_balk+2,2*nr_balk+2))

# Skapa elementmatriser. Eftersom alla delar är lika stora gör vi det en gång.
Ke1 = Ke_balk(EI,L)
Kesig1 = Ke_sigma_balk(P,L)

# Assemblera matriserna på rätt plats
for i in range(nr_balk):
    assem(K,Ke1,[2*i+1,2*i+2,2*i+3,2*i+4])
    assem(Ksig,Kesig1,[2*i+1,2*i+2,2*i+3,2*i+4])

# Definierar frihetsgraderna i en lista
dof_free = list(range(1,nr_balk*2+2+1))

# Tar bort frihetsgrader som inte ska vara med, nr 1 och näst-sista för Euler 2 t.ex.
dof_free.remove(1)
dof_free.remove(nr_balk*2+1)

# Extrahera de fria
Kred = extract_block(K,dof_free,dof_free)
Ksigred = extract_block(Ksig,dof_free,dof_free)

# Lös egenvärdesproblemet
alpha, a = eig(Kred,Ksigred)

# Jämför med teoretiska värden
displayvar('Euler_2',(3.1415/1)**2*EI)
sortOrder = np.argsort(alpha)
alpha = alpha[sortOrder]
a = a[:,sortOrder]
displayvar('α_1',np.real(alpha[0])*EI/(L*nr_balk)**2)
a1 = np.concatenate(([0],np.array(a[0:-1,0]),[0],a[-1:,0]))





<IPython.core.display.Math object>

<IPython.core.display.Math object>